fix: wandb login updating system settings even when failing login (#12332)
## Description

<!--
Include reference to internal ticket "Fixes WB-NNNNN" and/or GitHub issue "Fixes #NNNN" (if applicable)
-->

What does the PR do? Include a concise description of the PR contents.

Fixes a bug where `wandb verify` can get into a broken state when a bad host name is provided the first time.  
This happens because of two steps,  
First wandb.login was always updating the system settings even if the login failed (such as in the case of a bad hostname).  
The second issue arises from the fact that an `InternalApi` object is created (prior to wandb login), which validates the host name is formatted as a url.

The wandb login makes sense to only update on successful authentication to avoid changing the system settings when some inputs maybe invalid.  
The `IntenralApi` constructed in the `wandb verify` function is initially only used to read system settings prior to the wandb login step, this can be avoiding by using the `wandb_setup.singleton().settings`object,

<!--
NEW: We're using a new changelog format that's more useful for users. Please
see CHANGELOG.unreleased.md for details and update on relevant changes such as feature
additions, bug fixes, or removals/deprecations.
-->

- [ ] I updated CHANGELOG.unreleased.md, or it's not applicable

## Testing

How was this PR tested?

#### Verified that running wandb verify with invalid host does not update the settings file.

```bash
> wandb verify --host localhost:8080
Traceback (most recent call last):
  File "/Users/jacob.romero/.pyenv/versions/3.12.9/bin/wandb", line 6, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/jacob.romero/.pyenv/versions/3.12.9/lib/python3.12/site-packages/click/core.py", line 1569, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacob.romero/.pyenv/versions/3.12.9/lib/python3.12/site-packages/click/core.py", line 1490, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/jacob.romero/.pyenv/versions/3.12.9/lib/python3.12/site-packages/click/core.py", line 1970, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacob.romero/.pyenv/versions/3.12.9/lib/python3.12/site-packages/click/core.py", line 1353, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacob.romero/.pyenv/versions/3.12.9/lib/python3.12/site-packages/click/core.py", line 907, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacob.romero/.pyenv/versions/3.12.9/lib/python3.12/site-packages/wandb/cli/cli.py", line 3638, in verify
    wandb.login(host=host)
  File "/Users/jacob.romero/.pyenv/versions/3.12.9/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 100, in login
    logged_in, _ = _login(
                   ^^^^^^^
  File "/Users/jacob.romero/.pyenv/versions/3.12.9/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 167, in _login
    host_url = wbauth.HostUrl(host)
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacob.romero/.pyenv/versions/3.12.9/lib/python3.12/site-packages/wandb/sdk/lib/wbauth/host_url.py", line 28, in __init__
    urls.validate_url(url)
  File "/Users/jacob.romero/.pyenv/versions/3.12.9/lib/python3.12/site-packages/wandb/sdk/lib/urls.py", line 26, in validate_url
    _URL_VALIDATOR.validate_python(url)
pydantic_core._pydantic_core.ValidationError: 1 validation error for url['http','https']
  URL scheme should be 'http' or 'https' [type=url_scheme, input_value='localhost:8080', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/url_scheme
```

```bash
> cat ~/.config/wandb/settings
[default]

```

<!--
Ensure PR title compliance with the conventional commits standards:
https://github.com/wandb/wandb/blob/main/CONTRIBUTING.md#conventional-commits
-->