Add space before ';' in requirements_dev.txt
`pip` doesn't care, but `uv pip` is more strict, and without this change
attempting to install with `uv pip install -r requirements_dev.txt` results
in:

```
error: Couldn't parse requirement in `requirements_dev.txt` at position 1265
  Caused by: Missing space before ';', the end of the URL is ambiguous
.[sweeps]; sys_platform != 'darwin' or (sys_platform == 'darwin' and platform.machine != 'arm64')
```