chore: mark legacy-only and beta-only sync options (#12097)
Mark which `wandb sync` options are legacy-only and beta-only, and add the first beta-only option `--yes`. Using a legacy option forces legacy mode, and using a beta option in legacy mode causes the command to fail.

```
❯ wandb sync --legacy --yes  
Error: Not allowed in legacy mode: --yes

❯ wandb sync --sync-all --yes
wandb: Legacy mode was selected due to presence of legacy options. See --help for more info or use `wandb beta sync` directly.
Error: Not allowed in legacy mode: --yes
```

For `path`, I decided to remove the `len(path) >= 1` condition. The slight difference is that `wandb sync` used to be roughly the same as `wandb beta sync --dry-run --no-skip-online`, but now it prints out the runs it finds and prompts for confirmation. If prompting is not available (try with `TERM=dumb`), it raises a `NotATerminalError`, but using `wandb sync` in a non-interactive environment doesn't seem useful, so I don't think this is a breaking change.

 I didn't add docs about `tfevents` paths being legacy because that seems too in-depth, and the feature doesn't appear to be documented; someone who really wants to use a beta option can always use `wandb beta sync` directly.