fix(artifacts): avoid using global random instance for client id
We switched to use `random.choices` in https://github.com/wandb/wandb/pull/10819
If user set `random.seed` they would get `Invalid Client ID digest`.

```
ValueError: ArtifactSaver.createArtifact: returned error 400: {"data":{"createArtifact":null},"errors":[{"message":"Invalid Client ID digest","path":["createArtifact"]}]}
```