feat: skip missing runs in api quieries (#12176)
## Description

<!--
Include reference to internal ticket "Fixes WB-NNNNN" and/or GitHub issue "Fixes #NNNN" (if applicable)
-->

- Fixes WB-33595

What does the PR do? Include a concise description of the PR contents.

This PR adds a new feature to skip missing runs (rather than raise an error) when querying a collection of runs via `wandb.Api().runs()`.

Prior to this change when a collection of runs is loaded, the information is lazyily loaded, so if a run is removed between the time all runs are queried and when the actual run details itself is loaded an error would be raised. 

```
ValueError: Could not find run <Run internal-product-models/arene_detection_local/igor.vasiljevic-1776765424 (running)>
```

Now instead if the `on_missing` parameter is set to `skip`, the fields for the run will be set to empty values, and the state will be `missing`/

<!--
NEW: We're using a new changelog format that's more useful for users. Please
see CHANGELOG.unreleased.md for details and update on relevant changes such as feature
additions, bug fixes, or removals/deprecations.
-->

- [x] I updated [CHANGELOG.unreleased.md](http://CHANGELOG.unreleased.md), or it's not applicable

## Testing

How was this PR tested?

<!--
Ensure PR title compliance with the conventional commits standards:
https://github.com/wandb/wandb/blob/main/CONTRIBUTING.md#conventional-commits
-->