Update gitlib.py with better error handlign
## Description

Spent a day debugging why clearing my `tmp_path` with `pytest tests/loggers/test_wandb_logger.py -x -s -o tmp_path_retention_policy=failed` in the mosaicml [composer tests](https://github.com/mosaicml/composer/blob/9977bd60ea8f5e745b9b8f02eba0a3360900dd9c/tests/loggers/test_wandb_logger.py#L45-L46) where as `pytest tests/loggers/test_wandb_logger.py -x -s -o tmp_path_retention_policy=all` passes. 

Turns out this is the error log:

```
Thread HandlerThread:
Traceback (most recent call last):
  File "/Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
    self._process(record)
  File "/Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal.py", line 278, in _process
    self._hm.handle(record)
  File "/Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/handler.py", line 136, in handle
    handler(record)
  File "/Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/handler.py", line 146, in handle_request
    handler(record)
  File "/Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/handler.py", line 706, in handle_request_run_start
    self._system_monitor.probe(publish=True)
  File "/Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/system_monitor.py", line 207, in probe
    software_info: dict = self.system_info.probe()
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/system_info.py", line 230, in probe
    data = self._probe_git(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/system_info.py", line 177, in _probe_git
    if not self.git.enabled and self.git.auto:
           ^^^^^^^^^^^^^^^^
  File "/Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/gitlib.py", line 79, in enabled
    return bool(self.repo)
                ^^^^^^^^^
  File "/Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/gitlib.py", line 62, in repo
    self._repo = self._init_repo()
                 ^^^^^^^^^^^^^^^^^
  File "/Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/gitlib.py", line 51, in _init_repo
    return Repo(self._root or os.getcwd(), search_parent_directories=True)
                              ^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
wandb: ERROR Internal wandb error: file data was not synced
Problem at: /Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py 829 getcaller
E```

This PR makes it so that users don't have to set the WANDB_DISABLE_GIT flag if they decide to clear their pytest tmp_paths