chore: set TZ env var before running synctest (#11685)
Sets the timezone environment variable before invoking `synctest.Test` because this test started failing for me locally in pre-commit with a timestamp that's 8 hours off.


```
  --- FAIL: TestOpenDebugSyncLogFile (0.00s)
      logging_test.go:39: 
          	Error Trace:	/Users/timoffex/Documents/workspace/wandb/main/core/internal/runsync/logging_test.go:39
          	Error:      	Not equal: 
          	            	expected: "debug-sync.20000102.030405.log"
          	            	actual  : "debug-sync.20000101.190405.log"
```

I'm not really sure why this started to happen as there was no Go version update, and the test succeeds if I run it directly with `go test`. But it's pretty clear that the problem is timezone related.